AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Podcastr Api.

Resources:

  Feed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: podcastr.lambda_handler
      Runtime: python3.6
      Events:
        Feed:
          Type: Api
          Properties:
            Path: /
            Method: get
